name: SongTaoAds
services:
  redis:
    image: redis:7.2-alpine
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network
    restart: unless-stopped

  postgres:
    image: postgres:17.5-alpine3.21
    container_name: postgres
    hostname: postgres
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=SongTaoAds
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres-init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    restart: unless-stopped

  app:
    image: mthien1212/ads:latest
    container_name: songtao-ads
    ports:
      - "8080:8080"
      - "8888:8888"
    env_file: .env
    depends_on:
      redis:
        condition: service_started
      postgres:
        condition: service_started

    networks:
      - app-network

volumes:
  redis-data:
  postgres-data:

networks:
  app-network:
    driver: bridge