spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  application:
    name: ads
  datasource:
    url: ${DBMS_CONNECTION}
    username: ${DBMS_USERNAME}
    password: ${DBMS_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 50
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 20000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: 6379
      connect-timeout: 2000
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 2000
        shutdown-timeout: 1000
  cache:
    type: redis
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 100MB
  ai:
    openai:
      api-key: ${OPEN_AI_KEY}
      chat:
        options:
          model: ${OPEN_AI_MODEL_CHAT}
  threads:
    virtual:
      enabled: true

server:
  port: 8080
  tomcat:
    threads:
      max: 500
      min-spare: 15
    accept-count: 200

app:
  base:
    url: ${BASE_URL}
  jwt:
    signature: ${JWT_SIGNATURE}
    access-token-ttl: ${ACCESS_TOKEN_TTL}
    refresh-token-ttl: ${REFRESH_TOKEN_TTL}
  outbound:
    identity:
      client-id: ${GOOGLE_CLIENT_ID}
      client-secret: ${GOOGLE_CLIENT_SECRET}
      redirect-uri: ${GOOGLE_REDIRECT_URI}

payos:
  client-id: ${PAYOS_CLIENT_ID}
  api-key: ${PAYOS_API_KEY}
  checksum-key: ${PAYOS_CHECKSUM_KEY}

aws:
  region: ap-southeast-1
  bucket:
    name: ${AWS_S3_BUCKET}

stable-diffusion:
  url: ${STABLE_DIFFUSION_URL}
  token: ${STABLE_DIFFUSION_TOKEN}
  model-checkpoint: ${MODEL_CHECKPOINT}
  controlnet:
    module: ${CONTROLNET_MODEL}
    model: ${CONTROLNET_MODULE}
  pixel:
    max: ${STABLE_DIFFUSION_MAX_PIXEL}
    min: ${STABLE_DIFFUSION_MIN_PIXEL}

brevo:
  key: ${BREVO_KEY}
  sender-name: ${BREVO_SENDER_NAME}
  sender-email: ${BREVO_SENDER_EMAIL}
  verify-url: ${BREVO_VERIFY_URL}
  password-reset-url: ${BREVO_PASSWORD_RESET_URL}