spring:
  application:
    name: ads
  datasource:
    url: ${DBMS_CONNECTION}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: ${DBMS_USER}
    password: ${DBMS_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  data:
    redis:
      host: localhost
      port: 6379
      connect-timeout: 2000
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
server:
  port: 8080

#Local Variable
app:
  base:
    url: ${BASE_URL}
  jwt:
    signature: ${JWT_SIGNATURE}
    access-token-ttl: ${ACCESS_TOKEN_TTL}
    refresh-token-ttl: ${TOKEN_TOKEN_TTL}

