spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  application:
    name: ads
  datasource:
    url: ${DBMS_CONNECTION}
    username: ${DBMS_USERNAME}
    password: ${DBMS_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 3
      maximum-pool-size: 12
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 20000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: 6379
      connect-timeout: 2000
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 2
          max-wait: 2000
        shutdown-timeout: 1000
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 10MB

  ai:
    openai:
      api-key: ${OPEN_AI_KEY}

server:
  port: 8080
  tomcat:
    threads:
      max: 75
      min-spare: 15

app:
  base:
    url: ${BASE_URL}
  jwt:
    signature: ${JWT_SIGNATURE}
    access-token-ttl: ${ACCESS_TOKEN_TTL}
    refresh-token-ttl: ${REFRESH_TOKEN_TTL}

payos:
  CLIENT_ID: ${CLIENT_ID}
  API_KEY: ${API_KEY}
  CHECKSUM_KEY: ${CHECKSUM_KEY}
aws:
  region: ap-southeast-1
  bucket:
    name: songtaoads
stable-diffusion:
  url: ${STABLE_DIFFUSION_URL}
  token: ${STABLE_DIFFUSION_TOKEN}
brevo:
  key: ${BREVO_KEY}
  sender-name: ${SENDER_NAME}
  sender-email: ${SENDER_EMAIL}
  verify-url: ${VERIFY_URL}




