spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  application:
    name: ads
  datasource:
    url: ${DBMS_CONNECTION}
    username: ${DBMS_USERNAME}
    password: ${DBMS_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: 6379
      connect-timeout: 2000
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

server:
  port: 8080

app:
  base:
    url: ${BASE_URL}
  jwt:
    signature: ${JWT_SIGNATURE}
    access-token-ttl: ${ACCESS_TOKEN_TTL}
    refresh-token-ttl: ${TOKEN_TOKEN_TTL}

payos:
  CLIENT_ID: ${CLIENT_ID}
  API_KEYy: ${API_KEY}
  CHECKSUM_KEY: ${CHECKSUM_KEY}
  return-url: http://localhost:8080/api/v1/orders/payment-success
  cancel-url: http://localhost:8080/api/v1/orders/payment-cancel






