spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  application:
    name: ads
  datasource:
    url: ${DBMS_CONNECTION}
    username: ${DBMS_USERNAME}
    password: ${DBMS_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: 6379
      connect-timeout: 2000
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB
      file-size-threshold: 1B

server:
  port: 8080

app:
  base:
    url: ${BASE_URL}
  jwt:
    signature: ${JWT_SIGNATURE}
    access-token-ttl: ${ACCESS_TOKEN_TTL}
    refresh-token-ttl: ${REFRESH_TOKEN_TTL}

payos:
  CLIENT_ID: ${CLIENT_ID}
  API_KEY: ${API_KEY}
  CHECKSUM_KEY: ${CHECKSUM_KEY}
aws:
  region: ap-southeast-1
  bucket:
    name: songtaoads





