package com.capstone.ads.mapper;

import com.capstone.ads.dto.conversation.ConversationDTO;
import com.capstone.ads.model.Conversation;
import org.mapstruct.*;

@Mapper(componentModel = "spring")
public interface ConversationMapper {
    @Mapping(target = "topicId",source = "topic.id")
    @Mapping(target = "userId",source = "user.id")
    @Mapping(target = "modelChatBotId",source = "modelChatBot.id")
    ConversationDTO toDto(Conversation conversation);

    Conversation toEntity(ConversationDTO conversationDTO);

    @Mapping(target = "id", ignore = true) // ID will be generated by @GeneratedValue
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "updatedAt", ignore = true)
    Conversation createConversation(String topicId, String userId, String modelChatBotId);


}
