package com.capstone.ads.mapper;

import com.capstone.ads.dto.chatBot.ModelChatBotDTO;
import com.capstone.ads.model.ModelChatBot;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

@Mapper(componentModel = "spring")
public interface ModelChatBotMapper {
    @Mapping(target = "id", ignore = true) // ID is generated by JPA
    ModelChatBot toEntity(ModelChatBotDTO dto);

    ModelChatBotDTO toDTO(ModelChatBot entity);

}
