package com.capstone.ads.model.enums;

public enum CustomDesignRequestStatus {
    PENDING,
    PRICING_NOTIFIED,
    REJECTED_PRICING,
    APPROVED_PRICING,
    DEPOSITED,
    ASSIGNED_DESIGNER,
    PROCESSING,
    DESIGNER_REJECTED,
    DEMO_SUBMITTED,
    REVISION_REQUESTED,
    WAITING_FULL_PAYMENT,
    FULLY_PAID,
    COMPLETED,
    CANCELLED,
}
