package com.capstone.ads.model.enums;

public enum OrderStatus {
    PENDING_DESIGN,
    NEED_DEPOSIT_DESIGN,
    DEPOSITED_DESIGN,
    NEED_FULLY_PAID_DESIGN,
    WAITING_FINAL_DESIGN,
    DESIGN_COMPLETED,

    PENDING_CONTRACT,
    CONTRACT_SENT,
    CONTRACT_SIGNED,
    CONTRACT_DISCUSS,
    CONTRACT_RESIGNED,
    CONTRACT_CONFIRMED,

    DEPOSITED,
    IN_PROGRESS,
    PRODUCING,
    PRODUCTION_COMPLETED,
    DELIVERING,
    INSTALLED,
    ORDER_COMPLETED,
    CANCELLED
}
